### ISSUE TITLE
Reddit proof public key fingerprint appears broken

### ISSUE THREAD

**Issue by tlehman** [keybase/keybase-issues#1346]
I just did a [reddit proof that keybase:tlehman = reddit:habitmelon](https://www.reddit.com/r/KeybaseProofs/comments/2tgktl/my_keybase_proof_reddithabitmelon_keybasetlehman/), notice that under the public key fingerprint section, it says

    I have a public key whose fingerprint is RETU RN T HIS. PGP. GET_ FING ERPR INT( ); }

That is wrong, I also found some older proofs of other people's identities, such as [reddit:bitsandbooks = keybase:bitsandbooks](https://www.reddit.com/r/KeybaseProofs/comments/2tbiml/my_keybase_proof_redditbitsandbooks/)

    I have a public key whose fingerprint is BF02 A42C B992 9B01 5FC2 BB20 7C07 9884 F4CE FB5D

I have dug through the node-client source a bit, but I am not seeing where that line is generated.

**Comment by maxtaco** [comment]
Thanks for the bug report.  I must have broken this a few days ago.  Will fix. cc: @malgorithms

**Comment by adamrothman** [comment]
This is also happening for GitHub proofs: https://gist.github.com/adamrothman/280d191133a3e098443e

Interestingly it doesn't seem to affect the proving process. I was able to verify my GitHub account just fine.

**Comment by maxtaco** [comment]
Right the proof checker cares about the pgp Sig which contains your
fingerprint and the other important details.

**Comment by totokaka** [comment]
I believe this was fixed together with #1348

**Comment by adamrothman** [comment]
@maxtaco @totokaka So it looks like the fingerprint issue is indeed fixed but Reddit proof checking still seems to be broken. I just posted: https://www.reddit.com/r/KeybaseProofs/comments/2tn80a/my_keybase_proof_redditopticalfiber/ but Keybase isn't picking it up.

**Comment by totokaka** [comment]
I just verified reddit, and it worked: https://www.reddit.com/r/KeybaseProofs/comments/2tn87o/my_keybase_proof_reddittotokaka_keybasetotokaka/

**Comment by adamrothman** [comment]
Will give it another shot.

**Comment by adamrothman** [comment]
@totokaka How did you do it? I'm doing it through the browser and it's still failing. Here's my most recent post: https://www.reddit.com/r/KeybaseProofs/comments/2tnapz/my_keybase_proof_redditopticalfiber/

**Comment by adamrothman** [comment]
Command line isn't working for me either.

**Comment by dtiersch** [comment]
@adamrothman looks like you're shadow banned ([this](http://nullprogram.com/am-i-shadowbanned/#opticalfiber), [this](https://www.reddit.com/r/AskReddit/comments/11ggji/can_someone_please_explain_to_me_what_shadow/) and [this](https://www.quora.com/What-can-a-Reddit-user-do-about-a-Reddit-wide-shadowban))

**Comment by malgorithms** [comment]
Does that proof work now? I may have manually approved it.

**Comment by adamrothman** [comment]
@dtiersch You're right, I am. I messaged the admins and hopefully I'll be back in good standing soon.

@malgorithms Doesn't look like it, I think it's stuck because my account is invisible to the outside world.

**Comment by tlehman** [comment]
This is now fixed [new reddit proof correctly displays GPG fingerprint](https://www.reddit.com/r/KeybaseProofs/comments/2wwtef/my_keybase_proof_reddithabitmelon_keybasetlehman/) [closes #1346]
