### ISSUE TITLE
Starting a chat with myself, stuck on "Conversation needs to be rekeyed"

### ISSUE THREAD

**Issue by zapu** [keybase/keybase-issues#2827]
Steps to reproduce:
1. Start conversation with myself. I am `zapu` on Keybase, and I started new chat with `zapu`.
2. Send a message to myself (from `zapu` to `zapu`)
3. Add a new device (another computer).
4. Try to read that conversation from new computer.
5. "This conversation needs to be rekeyed.". When I click "Rekey" button, at first it seemed like it did not do anything, and I clicked multiple times. But after a while (30 seconds or so), multiple dialogs with "This computer and possibly others are unable to read some of your folders. To avoid losing data forever,..." appeared.

I think the rekey-ing itself works for me, because I have other conversation that I can see fine from both devices. But chatting with oneself might be a weird edge case.

**Comment by mlsteele** [comment]
Thanks for the report @zapu. Were both devices online during this debacle? Would you do a `keybase log send`, from both devices if possible? So your other conversations are working ok on both devices, what's the current state of the conversation with yourself on each device?

**Comment by zapu** [comment]
Hmm, now laptop (the second one added) wants to enter paper key "to rekey for kbfs". Both devices are on-line right now.

**Comment by zapu** [comment]
Log from main device: `4771a04ddee9ede01192051c`
Log from second device: `4eff1b63371ba068309ff41c`

The first device also had this warning:
```
- WARNING error occurred during reverse scan: token too long
```

but it had "Success!" in the end.

**Comment by zapu** [comment]
Looks like my folder has to be rekeyed as well. But nothing happens when I press "Rekey" in tray menu.

**Comment by zapu** [comment]
Apparently my folder is now working again. I've just put a file into private/ on laptop and was able to read it back on main PC.

**Comment by songgao** [comment]
Thanks for reporting!

Resolved by keybase/client#5850 and keybase/kbfs#760

**Comment by zapu** [comment]
Since this looks client-sided, I'll have to wait for the update to confirm, is that correct?

**Comment by maxtaco** [comment]
Indeed. We also think there is a race condition involved so it will be
difficult to directly confirm it's fixed.

**Comment by zapu** [comment]
OK, thank you. I'll try chatting again later today (I left my laptop at the office), I could reliably reproduce it there - the chat would always stay in "need rekey" state and rekeying would fail.

Maybe someone else can reproduce this: as described in 1st post, just chat with yourself. Or maybe this is a nonissue and chatting with oneself should be blocked on UI level.

**Comment by maxtaco** [comment]
Hmmmm it could be that you hit a further bug.  @sonngao can you check out
the log here?

**Comment by maxtaco** [comment]
... my expectation is that the bug we just fixed would resolve itself after
an hour without the fix

**Comment by songgao** [comment]
Hi @zapu, chatting with oneself should definitely be working. As Max said, issues caused by the bug we fixed should resolve themselves within short time. So this might be a different one. Would you mind doing another log send? Thanks!

**Comment by zapu** [comment]
OK, looks like it fixed itself, I've checked with both the main PC and laptop.

**Comment by songgao** [comment]
Thanks @zapu. I'm closing this again for now.

**Comment by zapu** [comment]
Thank you, sorry for the reopen. For my defense I can tell that it was still broken for me right after this PR was merged (that's why I asked if it needs update). It must have fixed itself afterwards.

**Comment by songgao** [comment]
No worries! It was the right thing to do to bring it up and thanks for doing so. I think that might have been because the local daemon was not connected to the servers yet.
